name: booklore
base: core24
version: '1.14.1'
summary: Single-line elevator pitch for your amazing snap
description: |
  BookLore is a self-hosted web app for organising and managing your personal book
  collection. It provides an intuitive interface to browse, read, and track your
  progress across PDFs and eBooks. With robust metadata management, multi-user
  support, and a sleek, modern UI, BookLore makes it easy to build and explore
  your personal library.

grade: devel
confinement: devmode

layout:
  /var/lib/nginx:
    bind: $SNAP_DATA/var/lib/nginx
  /var/log/nginx:
    bind: $SNAP_DATA/var/log/nginx

parts:
  booklore-api:
    plugin: nil
    source: https://github.com/booklore-app/booklore.git
    source-type: git
    source-depth: 1
    build-packages:
      - openjdk-21-jdk-headless
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - openjdk-21-jre-headless
      - ca-certificates
      - ca-certificates-java
    override-build: |
      echo "BEGIN BUILD OF Booklore - gradlew"
      export JAVA_HOME="${SNAPCRAFT_PART_INSTALL}/usr/lib/jvm/java-21-openjdk-${SNAP_ARCH}"
      cd booklore-api
      ./gradlew --no-daemon bootJar
      echo "COMPLETED BUILD OF Booklore - gradlew"
    override-stage: |
      printenv
      mkdir -p "${CRAFT_PRIME}"/bin
      cp -a ${CRAFT_PART_BUILD} ${SNAPCRAFT_PRIME}/bin/
      craftctl default
  
  # Server wrapper scripts
  server-wrappers:
    plugin: dump
    source: ./snap-wrappers
    stage-packages:
      - mariadb-server
    organize:
      mariadb-start-server: bin/mariadb-start-server
      booklore-start-server: bin/booklore-start-server
      nginx-start-server: bin/nginx-start-server
      
  # Booklore UI
  booklore-ui:
    plugin: nil
    source: https://github.com/booklore-app/booklore.git
    source-type: git
    source-depth: 1
    override-build: |
      echo "BEGIN BUILD OF Booklore - UI"
      cd booklore-ui
      
      # Download and install nvm:
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
      # in lieu of restarting the shell
      \. "$HOME/.nvm/nvm.sh"
      # Download and install Node.js:
      nvm install 24

      npm config set registry http://registry.npmjs.org
      npm install --force
      npm run build --configuration=production
      echo "COMPLETED BUILD OF Booklore - UI"
    override-stage: |
      printenv
      mkdir -p "${CRAFT_PRIME}"/booklore-ui/dist/booklore
      cp -a ${CRAFT_PART_BUILD} ${SNAPCRAFT_PRIME}/bin/
      craftctl default
  
  nginx:
    plugin: dump
    source: ./nginx
    stage-packages:
      - nginx
      - nginx-common
    organize:
      nginx.conf: etc/nginx-booklore/nginx.conf
    


apps:
  # MariaDB daemon
  mariadb-server:
    command: bin/mariadb-start-server
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

  booklore-api:
    command: bin/booklore-start-server
    daemon: simple
    after:
      - mariadb-server
    restart-condition: always
    plugs:
      - network
      - network-bind
      - system-observe
      - removable-media
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64/
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib
      JAVA_OPTS: -Djna.library.path=$SNAP/usr/lib/x86_64-linux-gnu/jni/libjnidispatch.system.so -Djna.tmpdir=/tmp
      DATABASE_URL: jdbc:mariadb://localhost:41933/booklore
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: ""
    
  # Nginx daemon
  nginx-server:
    command: bin/nginx-start-server
    daemon: simple
    after:
      - mariadb-server
      - booklore-api
    restart-condition: always
    plugs: [network, network-bind]
