#!/bin/bash
echo "Creating DB if it doesn't exist already..."
mariadb -h localhost -P 41933 --skip-ssl -u root -e "CREATE DATABASE IF NOT EXISTS booklore;"
${SNAP}/usr/lib/jvm/java-21-openjdk-amd64/bin/java -jar -Dserver.port=41934 $SNAP/bin/build/booklore-api/build/libs/booklore-api-0.0.1-SNAPSHOT.jar
