name: booklore
title: BookLore
license: GPL-3.0
website: https://github.com/booklore-app/booklore
donation: https://opencollective.com/booklore
source-code: https://github.com/booklore-app/booklore.git
issues: https://github.com/danbishop/booklore-snap/issues
contact: d@nbishop.uk
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]
adopt-info: booklore-api
summary: A self-hosted web app for organising your personal book collection
description: |
  BookLore is a self-hosted web app for organising and managing your personal book
  collection. It provides an intuitive interface to browse, read, and track your
  progress across PDFs and eBooks. With robust metadata management, multi-user
  support, and a sleek, modern UI, BookLore makes it easy to build and explore
  your personal library.
  
  **This is an unofficial snap.** After installing, and waiting for the the various services to start, your instance will be accessible at http://localhost:41935

  There are three services, nginx (the web server), booklore-api (the backend API server), and mariadb (the database server). The database files and logs are stored in the snap's data directory, which is preserved across snap updates.

  You can change the port that each service uses with the following commands:

  For the port that nginx listens on (default 41935):
  ```bash
  sudo snap set booklore port=<desired-port>
  ```
  
  For the port that MariaDB listens on (default 41936):
  ```bash
  sudo snap set booklore database-port=<desired-port>
  ```
  
  For the port that booklore-api listens on (default 41937):
  ```bash
  sudo snap set booklore api-port=<desired-port>
  ```
  
  After changing the ports, you will need to restart the snap for the changes to take effect:
  ```bash
  sudo snap restart booklore
  ```
  
  If you need to connect to the MariaDB database from outside the snap, the username is `booklore` and you can use the following command to get the password:
  ```bash
  snap get booklore database-password
  ``` 

  You can also connect with the following command as root:
  ```bash
  sudo mariadb --socket=/var/snap/booklore/common/run/mysql/mysqld.sock -u root --skip-ssl
  ```

grade: stable
confinement: strict

layout:
  /var/lib/nginx:
    bind: $SNAP_DATA/var/lib/nginx
  /var/log/nginx:
    bind: $SNAP_DATA/var/log/nginx

parts:
  booklore-api:
    plugin: nil
    source: https://github.com/booklore-app/booklore.git
    source-type: git
    build-packages:
      - openjdk-21-jdk-headless
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - openjdk-21-jre-headless
      - ca-certificates
      - ca-certificates-java
    override-build: |
      craftctl set version=$(git describe --tags $(git rev-list --tags --max-count=1))
      echo "BEGIN BUILD OF Booklore - gradlew"
      export JAVA_HOME="${SNAPCRAFT_PART_INSTALL}/usr/lib/jvm/java-21-openjdk-${SNAP_ARCH}"
      cd booklore-api
      if [ ! -z ${https_proxy+x} ]; then
        https_proxy_host=$(echo $https_proxy | cut -d'/' -f3 | cut -d':' -f1);
        https_proxy_port=$(echo $https_proxy | cut -d'/' -f3 | cut -d':' -f2);
        gradle_opts="-Dhttp.proxyHost=$https_proxy_host -Dhttp.proxyPort=$https_proxy_port -Dhttps.proxyHost=$https_proxy_host -Dhttps.proxyPort=$https_proxy_port";
      else
        gradle_opts="";
      fi
      ./gradlew --no-daemon $gradle_opts bootJar
      echo "COMPLETED BUILD OF Booklore - gradlew"
    override-stage: |
      printenv
      mkdir -p "${CRAFT_PRIME}"/bin
      cp -a ${CRAFT_PART_BUILD}/booklore-api/build ${SNAPCRAFT_PRIME}/bin/booklore-api
      craftctl default
  
  # Server wrapper scripts
  server-wrappers:
    plugin: dump
    source: ./snap-wrappers
    stage-packages:
      - mariadb-server
    organize:
      mariadb-start-server: bin/mariadb-start-server
      booklore-start-server: bin/booklore-start-server
      nginx-start-server: bin/nginx-start-server
      
  # Booklore UI
  booklore-ui:
    plugin: nil
    source: https://github.com/booklore-app/booklore.git
    source-type: git
    source-depth: 1
    build-packages:
      - wget
    override-build: |
      echo "BEGIN BUILD OF Booklore - UI"
      cd booklore-ui
      
      # Download and install nvm:
      wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
      # in lieu of restarting the shell
      \. "$HOME/.nvm/nvm.sh"
      # Download and install Node.js:
      nvm install 24

      npm config set registry http://registry.npmjs.org
      npm install --force
      npm run build --configuration=production
      echo "COMPLETED BUILD OF Booklore - UI"
    override-stage: |
      printenv
      mkdir -p "${CRAFT_PRIME}"/booklore-ui
      cp -a ${CRAFT_PART_BUILD}/booklore-ui/dist/booklore/browser/ "${CRAFT_PRIME}"/booklore-ui
      craftctl default
  
  nginx:
    plugin: dump
    source: ./nginx
    stage-packages:
      - nginx
      - nginx-common
      - gettext
    organize:
      nginx.conf.template: etc/nginx/nginx.conf.template

apps:
  # MariaDB daemon
  mariadb-server:
    command: bin/mariadb-start-server
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

  booklore-api:
    command: bin/booklore-start-server
    daemon: simple
    after:
      - mariadb-server
    restart-condition: always
    plugs:
      - network
      - network-bind
      # - system-observe
      - removable-media
      - mount-observe
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64/
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib
      JAVA_OPTS: -Djna.library.path=$SNAP/usr/lib/x86_64-linux-gnu/jni/libjnidispatch.system.so -Djna.tmpdir=/tmp
    
  # Nginx daemon
  nginx:
    command: bin/nginx-start-server
    daemon: simple
    after:
      - mariadb-server
      - booklore-api
    restart-condition: always
    plugs: [network, network-bind]

lint:
  ignore:
    - library